"""Pure JAX building blocks for device-resident F1TENTH simulation.

The functional environment is intentionally assembled in layers. This
namespace exposes pure dynamics, control, state, reference-line, reset,
geometry, sensing, episode, randomization, and batched-rollout kernels.
Host-only map extraction lives in :mod:`f1tenth_gym.jax.preprocess`, and
``EnvConfig`` conversion lives in the deep-import
:mod:`f1tenth_gym.jax.builder`. Gymnasium observation packaging is also a deep
import from :mod:`f1tenth_gym.jax.gym_observation`, and the host lifecycle is
:mod:`f1tenth_gym.jax.gym_env`. Importing this package does not resolve maps,
construct a Gymnasium environment, or initialize rendering.
"""

from .dynamics import (
    DynamicsParams,
    kinematic_single_track,
    single_track,
    standardize_state,
)
from .controls import (
    LongitudinalControlMode,
    SteeringControlMode,
    adapt_actions,
    speed_control,
    steering_angle_control,
)
from .core import (
    DynamicsConfig,
    DynamicsState,
    EpisodeParams,
    make_dynamics_state,
    rollout_dynamics,
    step_dynamics,
)
from .episode import (
    BookkeepingParams,
    BuiltinRewardMode,
    EpisodeConfig,
    EpisodeEvents,
    EpisodeMetrics,
    EpisodeState,
    EpisodeStatus,
    TerminationMode,
    advance_episode,
    reset_episode_state,
    wrap_progress_delta,
)
from .environment import (
    CoreConfig,
    CoreMetrics,
    CoreObservation,
    CoreParams,
    CoreState,
    CoreTables,
    observe_core,
    reset_core,
    reset_core_from_poses,
    reset_core_from_state,
    step_core,
)
from .randomization import (
    ACTIVE_VEHICLE_FIELDS,
    ActiveVehicleParams,
    VehicleRandomizationParams,
    domain_randomization_key,
    replace_core_vehicle_params,
    sample_core_params,
    sample_vehicle_params,
)
from .batched import (
    AutoResetBatchStep,
    BatchState,
    BatchStep,
    PolicyField,
    PolicyLayout,
    batch_action_bounds,
    flatten_joint_observation,
    policy_observation,
    reset_batch,
    reset_batch_from_poses,
    reset_batch_from_state,
    scale_normalized_actions,
    select_ego_rewards,
    step_batch,
    step_batch_autoreset,
)
from .indexed import (
    IndexedCoreTables,
    reset_indexed_batch,
    reset_indexed_batch_from_poses,
    reset_indexed_batch_from_state,
    stack_core_tables,
    step_indexed_batch,
    step_indexed_batch_autoreset,
)
from .contact import (
    ContactParams,
    WallContactConfig,
    apply_contact_response,
    resolve_wall_contacts,
    world_velocity,
)
from .integrators import euler_step, integrate_substeps, rk4_step
from .geometry import (
    BodyParams,
    body_vertices,
    collision_body_pose,
    transform_pose,
)
from .lidar import (
    ScanConfig,
    ScanParams,
    ScanState,
    beam_angles,
    clean_scan,
    lidar_poses,
    observed_scan,
    opponent_ranges,
    reset_scan_state,
)
from .pairs import (
    PairContactConfig,
    PairTable,
    make_pair_table,
    resolve_contacts,
    resolve_pair_contacts,
    solve_pair_impulses,
)
from .reset import (
    ResetConfig,
    ResetTable,
    model_state_from_poses,
    reset_dynamics_state,
    sample_reset_poses,
)
from .track import (
    FrenetProjectionConfig,
    SplineTable,
    TileTable,
    TrackTable,
    WallTable,
    cartesian_to_frenet,
    cartesian_to_frenet_local,
    evaluate_spline,
    frenet_to_cartesian,
    tile_candidates,
)

__all__ = [
    "ACTIVE_VEHICLE_FIELDS",
    "ActiveVehicleParams",
    "AutoResetBatchStep",
    "BatchState",
    "BatchStep",
    "BodyParams",
    "BookkeepingParams",
    "BuiltinRewardMode",
    "ContactParams",
    "CoreConfig",
    "CoreMetrics",
    "CoreObservation",
    "CoreParams",
    "CoreState",
    "CoreTables",
    "DynamicsConfig",
    "DynamicsParams",
    "DynamicsState",
    "EpisodeParams",
    "EpisodeConfig",
    "EpisodeEvents",
    "EpisodeMetrics",
    "EpisodeState",
    "EpisodeStatus",
    "FrenetProjectionConfig",
    "IndexedCoreTables",
    "LongitudinalControlMode",
    "PairContactConfig",
    "PairTable",
    "PolicyField",
    "PolicyLayout",
    "ResetConfig",
    "ResetTable",
    "ScanConfig",
    "ScanParams",
    "ScanState",
    "SplineTable",
    "SteeringControlMode",
    "TerminationMode",
    "TileTable",
    "TrackTable",
    "WallTable",
    "WallContactConfig",
    "VehicleRandomizationParams",
    "adapt_actions",
    "advance_episode",
    "apply_contact_response",
    "batch_action_bounds",
    "beam_angles",
    "body_vertices",
    "cartesian_to_frenet",
    "cartesian_to_frenet_local",
    "clean_scan",
    "collision_body_pose",
    "euler_step",
    "domain_randomization_key",
    "flatten_joint_observation",
    "integrate_substeps",
    "kinematic_single_track",
    "lidar_poses",
    "make_dynamics_state",
    "make_pair_table",
    "model_state_from_poses",
    "evaluate_spline",
    "frenet_to_cartesian",
    "opponent_ranges",
    "observe_core",
    "observed_scan",
    "reset_core",
    "reset_core_from_poses",
    "reset_core_from_state",
    "reset_batch",
    "reset_batch_from_poses",
    "reset_batch_from_state",
    "reset_dynamics_state",
    "reset_episode_state",
    "reset_indexed_batch",
    "reset_indexed_batch_from_poses",
    "reset_indexed_batch_from_state",
    "reset_scan_state",
    "resolve_wall_contacts",
    "resolve_contacts",
    "resolve_pair_contacts",
    "rk4_step",
    "rollout_dynamics",
    "single_track",
    "standardize_state",
    "stack_core_tables",
    "sample_reset_poses",
    "sample_core_params",
    "sample_vehicle_params",
    "scale_normalized_actions",
    "select_ego_rewards",
    "speed_control",
    "solve_pair_impulses",
    "steering_angle_control",
    "step_dynamics",
    "step_indexed_batch",
    "step_indexed_batch_autoreset",
    "step_core",
    "step_batch",
    "step_batch_autoreset",
    "tile_candidates",
    "transform_pose",
    "policy_observation",
    "replace_core_vehicle_params",
    "world_velocity",
    "wrap_progress_delta",
]
