"""Pure JAX building blocks for device-resident F1TENTH simulation.

The functional environment is intentionally assembled in layers. This
namespace exposes pure dynamics, control, state, reference-line, reset,
geometry, sensing, and episode kernels. Host-only map extraction lives in
:mod:`f1tenth_gym.jax.preprocess`, and ``EnvConfig`` conversion lives in the
deep-import :mod:`f1tenth_gym.jax.builder`. Gymnasium observation packaging is
also a deep import from :mod:`f1tenth_gym.jax.gym_observation`, and the host
lifecycle is :mod:`f1tenth_gym.jax.gym_env`. Importing this package does not
resolve maps, construct a Gymnasium environment, or initialize rendering.
"""

from .dynamics import (
    DynamicsParams,
    kinematic_single_track,
    single_track,
    standardize_state,
)
from .controls import (
    LongitudinalControlMode,
    SteeringControlMode,
    adapt_actions,
    speed_control,
    steering_angle_control,
)
from .core import (
    DynamicsConfig,
    DynamicsState,
    EpisodeParams,
    make_dynamics_state,
    rollout_dynamics,
    step_dynamics,
)
from .episode import (
    BookkeepingParams,
    BuiltinRewardMode,
    EpisodeConfig,
    EpisodeEvents,
    EpisodeMetrics,
    EpisodeState,
    EpisodeStatus,
    TerminationMode,
    advance_episode,
    reset_episode_state,
    wrap_progress_delta,
)
from .environment import (
    CoreConfig,
    CoreMetrics,
    CoreObservation,
    CoreParams,
    CoreState,
    CoreTables,
    observe_core,
    reset_core,
    reset_core_from_poses,
    reset_core_from_state,
    step_core,
)
from .contact import (
    ContactParams,
    WallContactConfig,
    apply_contact_response,
    resolve_wall_contacts,
    world_velocity,
)
from .integrators import euler_step, integrate_substeps, rk4_step
from .geometry import (
    BodyParams,
    body_vertices,
    collision_body_pose,
    transform_pose,
)
from .lidar import (
    ScanConfig,
    ScanParams,
    ScanState,
    beam_angles,
    clean_scan,
    lidar_poses,
    observed_scan,
    opponent_ranges,
    reset_scan_state,
)
from .pairs import (
    PairContactConfig,
    PairTable,
    make_pair_table,
    resolve_contacts,
    resolve_pair_contacts,
    solve_pair_impulses,
)
from .reset import (
    ResetConfig,
    ResetTable,
    model_state_from_poses,
    reset_dynamics_state,
    sample_reset_poses,
)
from .track import (
    FrenetProjectionConfig,
    SplineTable,
    TileTable,
    TrackTable,
    WallTable,
    cartesian_to_frenet,
    cartesian_to_frenet_local,
    evaluate_spline,
    frenet_to_cartesian,
    tile_candidates,
)

__all__ = [
    "BodyParams",
    "BookkeepingParams",
    "BuiltinRewardMode",
    "ContactParams",
    "CoreConfig",
    "CoreMetrics",
    "CoreObservation",
    "CoreParams",
    "CoreState",
    "CoreTables",
    "DynamicsConfig",
    "DynamicsParams",
    "DynamicsState",
    "EpisodeParams",
    "EpisodeConfig",
    "EpisodeEvents",
    "EpisodeMetrics",
    "EpisodeState",
    "EpisodeStatus",
    "FrenetProjectionConfig",
    "LongitudinalControlMode",
    "PairContactConfig",
    "PairTable",
    "ResetConfig",
    "ResetTable",
    "ScanConfig",
    "ScanParams",
    "ScanState",
    "SplineTable",
    "SteeringControlMode",
    "TerminationMode",
    "TileTable",
    "TrackTable",
    "WallTable",
    "WallContactConfig",
    "adapt_actions",
    "advance_episode",
    "apply_contact_response",
    "beam_angles",
    "body_vertices",
    "cartesian_to_frenet",
    "cartesian_to_frenet_local",
    "clean_scan",
    "collision_body_pose",
    "euler_step",
    "integrate_substeps",
    "kinematic_single_track",
    "lidar_poses",
    "make_dynamics_state",
    "make_pair_table",
    "model_state_from_poses",
    "evaluate_spline",
    "frenet_to_cartesian",
    "opponent_ranges",
    "observe_core",
    "observed_scan",
    "reset_core",
    "reset_core_from_poses",
    "reset_core_from_state",
    "reset_dynamics_state",
    "reset_episode_state",
    "reset_scan_state",
    "resolve_wall_contacts",
    "resolve_contacts",
    "resolve_pair_contacts",
    "rk4_step",
    "rollout_dynamics",
    "single_track",
    "standardize_state",
    "sample_reset_poses",
    "speed_control",
    "solve_pair_impulses",
    "steering_angle_control",
    "step_dynamics",
    "step_core",
    "tile_candidates",
    "transform_pose",
    "world_velocity",
    "wrap_progress_delta",
]
